from tests.TestScript.test_TestScript import TestScriptTestSuite
from tests.TestScript.test_TestCase import TestCaseTestSuite
from tests.TestScript.test_Step import StepTestSuite
from tests.TestScript.test_Executor import ExecutorTestSuite
